DEBUG = True

USERNAME = 'root'
PASSWORD = '8Ns~*P^aV6t?aec'
SERVER = 'localhost'
DB = 'api_flask'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'


SQLALCHEMY_TRACK_MODIFICATIONS = True
