DEBUG = True

USERNAME = '*****'
PASSWORD = '*****'
SERVER = '127.0.0.1:5000'
DB = 'api_flask'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'


SQLALCHEMY_TRACK_MODIFICATIONS = True
