"""empty message

Revision ID: 639ab463551d
Revises: 8f229bd323ac
Create Date: 2023-08-16 19:44:20.807950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639ab463551d'
down_revision = '8f229bd323ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('formacao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.drop_column('curso', 'formacao_id')
    # ### end Alembic commands ###
