"""empty message

Revision ID: 9bb546b537a8
Revises: 
Create Date: 2023-08-13 20:00:16.961277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bb546b537a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curso', 'nome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('curso', 'descricao',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('curso', 'data_publicacao',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curso', 'data_publicacao',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('curso', 'descricao',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('curso', 'nome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
