"""empty message

Revision ID: 9e6a20ff3297
Revises: c44fdd6f67fb
Create Date: 2023-08-20 18:56:24.710302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e6a20ff3297'
down_revision = 'c44fdd6f67fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('formacao', 'idade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formacao', sa.Column('idade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('professores')
    # ### end Alembic commands ###
